
image: registry.gitlab.com/beverage-tastings/beverage-tastings/ci:1

services:
  - docker:stable-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .cache/pip

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  stage: build
  script:
    - cp beverage_tasting/.env.example beverage_tasting/.env
    - docker-compose build --no-cache
    - docker-compose up -d

test:
  stage: test
  script:
    - echo "hello world"

deploy:
  stage: deploy
  script:
    - mkdir $DOCKER_CERT_PATH
    - echo "$CA" > $DOCKER_CERT_PATH/ca.pem
    - echo "$CLIENT_CERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$CLIENT_KEY" > $DOCKER_CERT_PATH/key.pem
    - docker-compose -f docker-compose.yml up -d --force-recreate
    - rm -rf $DOCKER_CERT_PATH
  variables:
    DOCKER_TLS_VERIFY: "1"
    DOCKER_HOST: "TODO"
    DOCKER_CERT_PATH: "certs"
  when: manual
